/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.Color;

/**
 *
 * @author enzor
 */
public class InicioSesion extends javax.swing.JFrame {
    
    int xMouse, yMouse, xMouse1, yMouse2;
    
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        nombreEmpresa = new javax.swing.JLabel();
        jLabelIniciarSesion = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        extButton = new javax.swing.JPanel();
        extLabel = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelPass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelIngresar = new javax.swing.JPanel();
        ingresar = new javax.swing.JLabel();
        color2 = new javax.swing.JLabel();
        Color = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(210, 194, 179));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\enzor\\Downloads\\Proyecto\\src\\main\\java\\Imagenes\\Logo (1).png")); // NOI18N
        logo.setText("jLabel1");
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 150, 110));

        nombreEmpresa.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        nombreEmpresa.setForeground(new java.awt.Color(51, 51, 51));
        nombreEmpresa.setText("Nombre Empresa");
        bg.add(nombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        jLabelIniciarSesion.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabelIniciarSesion.setForeground(new java.awt.Color(204, 204, 204));
        jLabelIniciarSesion.setText("INICIAR SESION");
        bg.add(jLabelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        header.setBackground(new java.awt.Color(210, 194, 179));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        extButton.setBackground(new java.awt.Color(210, 194, 179));

        extLabel.setBackground(new java.awt.Color(210, 194, 179));
        extLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        extLabel.setForeground(new java.awt.Color(0, 0, 0));
        extLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extLabel.setText("X");
        extLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        extLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout extButtonLayout = new javax.swing.GroupLayout(extButton);
        extButton.setLayout(extButtonLayout);
        extButtonLayout.setHorizontalGroup(
            extButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
        extButtonLayout.setVerticalGroup(
            extButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addComponent(extButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addComponent(extButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 410, 30));

        header2.setBackground(new java.awt.Color(51, 51, 51));
        header2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header2MouseDragged(evt);
            }
        });
        header2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        jLabelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUsuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsuario.setText("USUARIO");
        bg.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 100, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuario.setText("Ingrese su nombre de usuario");
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        bg.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 430, -1));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 310, 10));

        jLabelPass.setBackground(new java.awt.Color(102, 102, 102));
        jLabelPass.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPass.setText("CONTRASEÑA");
        bg.add(jLabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 100, -1));

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("***********");
        jPasswordField1.setBorder(null);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        bg.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 310, -1));

        jPanelIngresar.setBackground(new java.awt.Color(243, 117, 14));
        jPanelIngresar.setForeground(new java.awt.Color(243, 117, 14));

        ingresar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        ingresar.setForeground(new java.awt.Color(51, 51, 51));
        ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresar.setText("INGRESAR");
        ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelIngresarLayout = new javax.swing.GroupLayout(jPanelIngresar);
        jPanelIngresar.setLayout(jPanelIngresarLayout);
        jPanelIngresarLayout.setHorizontalGroup(
            jPanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanelIngresarLayout.setVerticalGroup(
            jPanelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(jPanelIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 110, 50));

        color2.setIcon(new javax.swing.ImageIcon("C:\\Users\\enzor\\Downloads\\333333.png")); // NOI18N
        bg.add(color2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 500, 240));

        Color.setIcon(new javax.swing.ImageIcon("C:\\Users\\enzor\\Downloads\\333333.png")); // NOI18N
        bg.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void header2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header2MousePressed

    private void header2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header2MouseDragged

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void extLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_extLabelMouseClicked

    private void extLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extLabelMouseEntered
        extButton.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_extLabelMouseEntered

    private void ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseEntered
        jPanelIngresar.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_ingresarMouseEntered

    private void extLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extLabelMouseExited
        extButton.setBackground(new Color(210,194,179));
    }//GEN-LAST:event_extLabelMouseExited

    private void ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseExited
        jPanelIngresar.setBackground(new Color(243,117,14)); 
    }//GEN-LAST:event_ingresarMouseExited

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        jTextFieldUsuario.setText("");
        jPasswordField1.setText("***********");
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        jTextFieldUsuario.setText("Ingrese su nombre de usuario");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        jTextFieldUsuario.setText("");
        jPasswordField1.setText("***********");
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        jTextFieldUsuario.setText("Ingrese su nombre de usuario");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseClicked
        Interfaz panelMenu = new Interfaz();
        panelMenu.setPanel1(this);
        panelMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ingresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Color;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel color2;
    private javax.swing.JPanel extButton;
    private javax.swing.JLabel extLabel;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header2;
    private javax.swing.JLabel ingresar;
    private javax.swing.JLabel jLabelIniciarSesion;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelIngresar;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombreEmpresa;
    // End of variables declaration//GEN-END:variables
}
